[
  {
    item_name: "Asperges amande fumee",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "25 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
  },
  {
    item_name: "Tartare betterave capres",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "20 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
  },
  {
    item_name: "Veloute topinambour",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "30 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1604908176997-431c13a6c98f",
  },
  {
    item_name: "Carpaccio courgette citron",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "20 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    item_name: "Tarte porcini fine",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "35 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1525755662778-989d0524087e",
  },
  {
    item_name: "Raviole legumes grilles",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "40 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
  },
  {
    item_name: "Foie gras vegetal maison",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "45 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    item_name: "Lentilles beluga tiedes",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "30 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Ceviche vegetal coco",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "25 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae",
  },
  {
    item_name: "Creme brulee salee cepes",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "45 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1604908176997-431c13a6c98f",
  },
  {
    item_name: "Terrine legumes racines",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "40 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    item_name: "Veloute butternut gingembre",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "30 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1604908176997-431c13a6c98f",
  },
  {
    item_name: "Cromesquis tofu fume",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "35 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
  },
  {
    item_name: "Tian legumes provencaux",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "30 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Soupe concombre aneth",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "20 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae",
  },
  {
    item_name: "Tomates anciennes basilic",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "20 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    item_name: "Risotto vegetal croustillant",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "35 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Houmous pois chiches noirs",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "20 minutes",
    in_stock: 25,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
  },
  {
    item_name: "Millefeuille aubergine",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "40 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    item_name: "Gaspacho tomate framboise",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "20 minutes",
    in_stock: 25,
    image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae",
  },
  {
    item_name: "Salade fenouil orange",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "20 minutes",
    in_stock: 25,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Creme petits pois menthe",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "30 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1604908176997-431c13a6c98f",
  },
  {
    item_name: "Tataki pasteque tamari",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "25 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
  },
  {
    item_name: "Pate en croute vegetal",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "45 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    item_name: "Tartare avocat citron vert",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "20 minutes",
    in_stock: 25,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
  },
  {
    item_name: "Rouleaux printemps premium",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "30 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae",
  },
  {
    item_name: "Soupe miso cepes",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "30 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1604908176997-431c13a6c98f",
  },
  {
    item_name: "Creme artichaut truffee",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "35 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Quinoa royal herbes fraiches",
    item_type: "starter",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "3 hours",
    diet_type: "Vegan",
    min_preparation_time: "25 minutes",
    in_stock: 25,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },

  {
    item_name: "Wellington vegetal truffe",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "90 minutes",
    in_stock: 8,
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947",
  },
  {
    item_name: "Risotto cepes porcini",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "60 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Ravioli ricotta vegetale",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "75 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
  },
  {
    item_name: "Steak aubergine miso",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "50 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    item_name: "Puree celeri truffe",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "45 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
  },
  {
    item_name: "Gnocchi patate sauge",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "60 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
  },
  {
    item_name: "Couscous royal vegetal",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "75 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae",
  },
  {
    item_name: "Ratatouille confite premium",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "70 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    item_name: "Tofu grille sauce vin rouge",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "55 minutes",
    in_stock: 18,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
  },
  {
    item_name: "Polenta creme champignons",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "50 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Paella vegetale safran",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "80 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
  },
  {
    item_name: "Lasagnes legumes grillees",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "85 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
  },
  {
    item_name: "Burger gastronomique vegan",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "45 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349",
  },
  {
    item_name: "Curry coco patate douce",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "60 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae",
  },
  {
    item_name: "Quiche epinards vegan",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "70 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
  },
  {
    item_name: "Bourguignon vegetal",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "120 minutes",
    in_stock: 8,
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947",
  },
  {
    item_name: "Riz sauvage legumes rôtis",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "55 minutes",
    in_stock: 18,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Tajine pois chiches abricot",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "75 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae",
  },
  {
    item_name: "Ramen gourmet vegetal",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "70 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
  },
  {
    item_name: "Risotto citron asperges",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "60 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Tofu laque sesame",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "50 minutes",
    in_stock: 18,
    image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
  },
  {
    item_name: "Pates fraiches truffe",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "75 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
  },
  {
    item_name: "Cote chou fleur roti",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "60 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  },
  {
    item_name: "Moussaka vegetale",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "90 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
  },
  {
    item_name: "Gnocchi patate douce",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "60 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
  },
  {
    item_name: "Risotto safran citron",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "65 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
  },
  {
    item_name: "Feuille vigne farcie",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "70 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae",
  },
  {
    item_name: "Canneloni ricotta vegan",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "80 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
  },
  {
    item_name: "Chili gourmet vegetal",
    item_type: "main",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hour",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "90 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1559847844-5315695dadae",
  },

  {
    item_name: "Fondant chocolat intense",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "45 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1605478520058-3b2b1f5f3f8e",
  },
  {
    item_name: "Tarte citron meringuee vegan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "90 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1565958011703-44f9829ba187",
  },
  {
    item_name: "Creme brulee vanille",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "60 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
  },
  {
    item_name: "Mousse chocolat grand cru",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "30 minutes",
    in_stock: 25,
    image_url: "https://images.unsplash.com/photo-1605478520058-3b2b1f5f3f8e",
  },
  {
    item_name: "Tiramisu cafe vegan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "70 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb",
  },
  {
    item_name: "Paris brest vegetal",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "110 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
  },
  {
    item_name: "Opera chocolat cafe",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "120 minutes",
    in_stock: 8,
    image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb",
  },
  {
    item_name: "Cheesecake coco vegan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "80 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1505253213348-cd54c92b37c6",
  },
  {
    item_name: "Pavlova fruits rouges",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "75 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1505253213348-cd54c92b37c6",
  },
  {
    item_name: "Tarte fraise basilic",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "90 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea",
  },
  {
    item_name: "Profiteroles chocolat",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "100 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af",
  },
  {
    item_name: "Crumble pomme cannelle",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "50 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1505253213348-cd54c92b37c6",
  },
  {
    item_name: "Gateau pistache framboise",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "95 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
  },
  {
    item_name: "Moelleux noisette vegan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "60 minutes",
    in_stock: 18,
    image_url: "https://images.unsplash.com/photo-1605478520058-3b2b1f5f3f8e",
  },
  {
    item_name: "Sorbet mangue passion",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "40 minutes",
    in_stock: 30,
    image_url: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea",
  },
  {
    item_name: "Millefeuille vanille vegan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "120 minutes",
    in_stock: 8,
    image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb",
  },
  {
    item_name: "Brownie noix pecan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "55 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1605478520058-3b2b1f5f3f8e",
  },
  {
    item_name: "Tarte poire chocolat",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "85 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea",
  },
  {
    item_name: "Gateau amande fleur oranger",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "70 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
  },
  {
    item_name: "Choux praline vegan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "100 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af",
  },
  {
    item_name: "Panna cotta coco",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "50 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1505253213348-cd54c92b37c6",
  },
  {
    item_name: "Eclair chocolat vegan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "110 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af",
  },
  {
    item_name: "Financier amande vegan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "45 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
  },
  {
    item_name: "Cake citron pavot",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "60 minutes",
    in_stock: 20,
    image_url: "https://images.unsplash.com/photo-1605478520058-3b2b1f5f3f8e",
  },
  {
    item_name: "Macaron framboise vegan",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "120 minutes",
    in_stock: 10,
    image_url: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea",
  },
  {
    item_name: "Sorbet citron basilic",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "40 minutes",
    in_stock: 25,
    image_url: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea",
  },
  {
    item_name: "Tarte figue noix",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "90 minutes",
    in_stock: 12,
    image_url: "https://images.unsplash.com/photo-1505253213348-cd54c92b37c6",
  },
  {
    item_name: "Gateau chocolat noir intense",
    item_type: "dessert",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "80 minutes",
    in_stock: 15,
    image_url: "https://images.unsplash.com/photo-1605478520058-3b2b1f5f3f8e",
  },

  {
    item_name: "Champagne brut prestige",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 40,
    image_url: "https://images.unsplash.com/photo-1514361892635-eae31d0e8d6f",
  },
  {
    item_name: "Champagne rose grand cru",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 30,
    image_url: "https://images.unsplash.com/photo-1514361892635-eae31d0e8d6f",
  },
  {
    item_name: "Bourgogne pinot noir",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 50,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
  },
  {
    item_name: "Saint emilion reserve",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 40,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
  },
  {
    item_name: "Chablis premier cru",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 45,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
  },
  {
    item_name: "Sancerre blanc",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 35,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
  },
  {
    item_name: "Bordeaux rouge superieur",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 50,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
  },
  {
    item_name: "Cotes du rhone bio",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 45,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
  },
  {
    item_name: "Prosecco superiore",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 40,
    image_url: "https://images.unsplash.com/photo-1514361892635-eae31d0e8d6f",
  },
  {
    item_name: "Rose de provence",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 40,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
  },
  {
    item_name: "Irish coffee vegan",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "10 minutes",
    in_stock: 30,
    image_url: "https://images.unsplash.com/photo-1511920170033-f8396924c348",
  },
  {
    item_name: "Espresso arabica",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "3 minutes",
    in_stock: 100,
    image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
  },
  {
    item_name: "Cappuccino vegetal",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "2 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 80,
    image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
  },
  {
    item_name: "The vert sencha",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "1 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 100,
    image_url: "https://images.unsplash.com/photo-1518972559570-7cc1309f3229",
  },
  {
    item_name: "The noir earl grey",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "1 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 100,
    image_url: "https://images.unsplash.com/photo-1518972559570-7cc1309f3229",
  },
  {
    item_name: "Infusion verveine",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "1 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 80,
    image_url: "https://images.unsplash.com/photo-1518972559570-7cc1309f3229",
  },
  {
    item_name: "Eau minerale plate",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "1 minute",
    in_stock: 200,
    image_url: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc",
  },
  {
    item_name: "Eau minerale gazeuse",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "1 minute",
    in_stock: 200,
    image_url: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc",
  },
  {
    item_name: "Jus orange frais",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 60,
    image_url: "https://images.unsplash.com/photo-1506806732259-39c2d0268443",
  },
  {
    item_name: "Jus pomme artisanal",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 60,
    image_url: "https://images.unsplash.com/photo-1506806732259-39c2d0268443",
  },
  {
    item_name: "Mocktail basilic citron",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "1 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "8 minutes",
    in_stock: 50,
    image_url: "https://images.unsplash.com/photo-1514361892635-eae31d0e8d6f",
  },
  {
    item_name: "Mocktail framboise gingembre",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "1 hours",
    served_between_end: "5 hours",
    diet_type: "Vegan",
    min_preparation_time: "8 minutes",
    in_stock: 50,
    image_url: "https://images.unsplash.com/photo-1514361892635-eae31d0e8d6f",
  },
  {
    item_name: "Limonade artisanale",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "4 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 80,
    image_url: "https://images.unsplash.com/photo-1506806732259-39c2d0268443",
  },
  {
    item_name: "Vin blanc chardonnay",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 50,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
  },
  {
    item_name: "Vin rouge cabernet",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "0 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 50,
    image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
  },
  {
    item_name: "Digestif cognac vegan",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "3 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "3 minutes",
    in_stock: 25,
    image_url: "https://images.unsplash.com/photo-1582450871972-ab5ca6b1f6c4",
  },
  {
    item_name: "Liqueur framboise",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "3 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "3 minutes",
    in_stock: 30,
    image_url: "https://images.unsplash.com/photo-1582450871972-ab5ca6b1f6c4",
  },
  {
    item_name: "The blanc jasmin",
    item_type: "drink",
    min_no_persons: 2,
    is_active: true,
    served_between_start: "1 hours",
    served_between_end: "6 hours",
    diet_type: "Vegan",
    min_preparation_time: "5 minutes",
    in_stock: 90,
    image_url: "https://images.unsplash.com/photo-1518972559570-7cc1309f3229",
  },
];
