import { pgPool } from "./config/db.js";

const vaganData = [
  {
    item_code: "IT030",
    item_name: "Risotto crémeux aux cèpes",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/risotto_cepes.jpg",
  },
  {
    item_code: "IT031",
    item_name: "Bourguignon végétal aux champignons",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/bourguignon_vegetal.jpg",
  },
  {
    item_code: "IT032",
    item_name: "Parmentier de lentilles",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/parmentier_lentilles.jpg",
  },
  {
    item_code: "IT033",
    item_name: "Ratatouille confite, quinoa",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/ratatouille_quinoa.jpg",
  },
  {
    item_code: "IT034",
    item_name: "Tatin salée d’oignons caramélisés",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/tatin_oignons.jpg",
  },
  {
    item_code: "IT035",
    item_name: "Lasagnes végétales aux légumes rôtis",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/lasagnes_vegetales.jpg",
  },
  {
    item_code: "IT036",
    item_name: "Blanquette végétale aux légumes racines",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/blanquette_vegetale.jpg",
  },
  {
    item_code: "IT037",
    item_name: "Polenta crémeuse, champignons sauvages",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/polenta_champignons.jpg",
  },
  {
    item_code: "IT038",
    item_name: "Ravioles végétales aux épinards",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/ravioles_epinards.jpg",
  },
  {
    item_code: "IT039",
    item_name: "Gnocchis de pomme de terre, sauce truffée",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/gnocchis_truffe.jpg",
  },
  {
    item_code: "IT040",
    item_name: "Couscous végétal aux légumes grillés",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/couscous_vegetal.jpg",
  },
  {
    item_code: "IT041",
    item_name: "Steak de chou-fleur rôti",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/steak_choufleur.jpg",
  },
  {
    item_code: "IT042",
    item_name: "Pavé de tofu mariné, légumes glacés",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/tofu_legumes.jpg",
  },
  {
    item_code: "IT043",
    item_name: "Tarte fine aux légumes grillés",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/tarte_fine_legumes.jpg",
  },
  {
    item_code: "IT044",
    item_name: "Tourte forestière végétale",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/tourte_forestiere.jpg",
  },
  {
    item_code: "IT045",
    item_name: "Médaillon de céleri-rave rôti",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/celeri_rave_roti.jpg",
  },
  {
    item_code: "IT046",
    item_name: "Riz pilaf légumes & amandes",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/riz_pilaf.jpg",
  },
  {
    item_code: "IT047",
    item_name: "Aubergine rôtie, sauce tahini",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/aubergine_tahini.jpg",
  },
  {
    item_code: "IT048",
    item_name: "Galette de sarrasin aux légumes",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/galette_sarrasin.jpg",
  },
  {
    item_code: "IT049",
    item_name: "Ravioles aux cèpes, jus réduit",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/ravioles_cepes.jpg",
  },
  {
    item_code: "IT050",
    item_name: "Tarte tatin de légumes racines",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/tatin_legumes_racines.jpg",
  },
  {
    item_code: "IT051",
    item_name: "Riz pilaf citron & herbes",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/riz_pilaf_citron.jpg",
  },
  {
    item_code: "IT052",
    item_name: "Poêlée de champignons porcini, polenta",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/poelee_porcini_polenta.jpg",
  },
  {
    item_code: "IT053",
    item_name: "Légumes rôtis, sauce vierge",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/legumes_roti_sauce_vierge.jpg",
  },
  {
    item_code: "IT054",
    item_name: "Gratin dauphinois végétal",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/gratin_dauphinois_vegan.jpg",
  },
  {
    item_code: "IT055",
    item_name: "Curry doux de légumes façon française",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/curry_doux.jpg",
  },
  {
    item_code: "IT056",
    item_name: "Pavé végétal aux herbes, jus au thym",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/pave_vegetal_thym.jpg",
  },
  {
    item_code: "IT057",
    item_name: "Risotto asperges vertes",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/risotto_asperges.jpg",
  },
  {
    item_code: "IT058",
    item_name: "Filet végétal, sauce vin blanc",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/filet_vegetal_vin_blanc.jpg",
  },

  {
    item_code: "IT030",
    item_name: "Bourguignon végétal aux cèpes",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/bourguignon_vegetal.jpg",
  },
  {
    item_code: "IT031",
    item_name: "Risotto crémeux aux asperges",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/risotto_asperges.jpg",
  },
  {
    item_code: "IT032",
    item_name: "Parmentier végétal patate douce",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/parmentier_patate_douce.jpg",
  },
  {
    item_code: "IT033",
    item_name: "Ratatouille provençale revisitée",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/ratatouille.jpg",
  },
  {
    item_code: "IT034",
    item_name: "Côtelettes végétales sauce vin rouge",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/cotelettes_vegetales.jpg",
  },
  {
    item_code: "IT035",
    item_name: "Gratin dauphinois végétal",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/gratin_dauphinois.jpg",
  },
  {
    item_code: "IT036",
    item_name: "Tajine légumes confits",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/tajine_legumes.jpg",
  },
  {
    item_code: "IT037",
    item_name: "Lasagnes aux légumes grillés",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/lasagnes_vegetales.jpg",
  },
  {
    item_code: "IT038",
    item_name: "Risotto aux cèpes et truffe",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/risotto_cepes.jpg",
  },
  {
    item_code: "IT039",
    item_name: "Purée maison & légumes rôtis",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/puree_legumes.jpg",
  },
  {
    item_code: "IT040",
    item_name: "Polenta crémeuse aux champignons",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/polenta_champignons.jpg",
  },
  {
    item_code: "IT041",
    item_name: "Blanquette végétale",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/blanquette_vegetale.jpg",
  },
  {
    item_code: "IT042",
    item_name: "Filet végétal sauce poivre vert",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/filet_vegetal.jpg",
  },
  {
    item_code: "IT043",
    item_name: "Curry doux de légumes français",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/curry_legumes.jpg",
  },
  {
    item_code: "IT044",
    item_name: "Tarte salée légumes de saison",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/tarte_legumes.jpg",
  },
  {
    item_code: "IT045",
    item_name: "Risotto safrané aux légumes",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/risotto_safran.jpg",
  },
  {
    item_code: "IT046",
    item_name: "Steak végétal sauce forestière",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/steak_forestier.jpg",
  },
  {
    item_code: "IT047",
    item_name: "Pavé de tofu mariné grillé",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/tofu_grille.jpg",
  },
  {
    item_code: "IT048",
    item_name: "Paëlla végétale",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/paella_vegetale.jpg",
  },
  {
    item_code: "IT049",
    item_name: "Wellington végétal",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/wellington_vegetal.jpg",
  },
  {
    item_code: "IT050",
    item_name: "Pâtes fraîches sauce tomate confite",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/pates_tomate.jpg",
  },
  {
    item_code: "IT051",
    item_name: "Quinoa rôti aux légumes grillés",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/quinoa_grille.jpg",
  },
  {
    item_code: "IT052",
    item_name: "Gratin de courgettes amande",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/gratin_courgette.jpg",
  },
  {
    item_code: "IT053",
    item_name: "Chou farci végétal",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/chou_farci.jpg",
  },
  {
    item_code: "IT054",
    item_name: "Risotto citron basilic",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/risotto_citron.jpg",
  },
  {
    item_code: "IT055",
    item_name: "Cassoulet végétal revisité",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/cassoulet_vegetal.jpg",
  },
  {
    item_code: "IT056",
    item_name: "Galette sarrasin légumes grillés",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/galette_sarrasin.jpg",
  },
  {
    item_code: "IT057",
    item_name: "Burger gourmet végétal",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/burger_vegetal.jpg",
  },
  {
    item_code: "IT058",
    item_name: "Boulettes végétales sauce tomate",
    item_type: "main",
    diet_type: "Vegan",
    image: "/images/items/boulettes_vegetales.jpg",
  },

  {
    item_code: "IT059",
    item_name: "Crème brûlée végétale vanille",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/creme_brulee_vegan.jpg",
  },
  {
    item_code: "IT060",
    item_name: "Mousse au chocolat noir 70%",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/mousse_chocolat.jpg",
  },
  {
    item_code: "IT061",
    item_name: "Tarte fine aux pommes",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tarte_pommes.jpg",
  },
  {
    item_code: "IT062",
    item_name: "Poire pochée au vin rouge",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/poire_pochee_vin.jpg",
  },
  {
    item_code: "IT063",
    item_name: "Pavlova végétale fruits rouges",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/pavlova_vegan.jpg",
  },
  {
    item_code: "IT064",
    item_name: "Panna cotta coco & fruits rouges",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/panna_cotta_coco.jpg",
  },
  {
    item_code: "IT065",
    item_name: "Fondant chocolat noir",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/fondant_chocolat.jpg",
  },
  {
    item_code: "IT066",
    item_name: "Tarte citron végétale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tarte_citron.jpg",
  },
  {
    item_code: "IT067",
    item_name: "Sorbet citron",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/sorbet_citron.jpg",
  },
  {
    item_code: "IT068",
    item_name: "Sorbet framboise",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/sorbet_framboise.jpg",
  },
  {
    item_code: "IT069",
    item_name: "Tiramisu végétal",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tiramisu_vegan.jpg",
  },
  {
    item_code: "IT070",
    item_name: "Brownie vegan aux noix",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/brownie_noix.jpg",
  },
  {
    item_code: "IT071",
    item_name: "Compote pomme-cannelle maison",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/compote_pomme.jpg",
  },
  {
    item_code: "IT072",
    item_name: "Fraises & crème fouettée végétale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/fraises_creme.jpg",
  },
  {
    item_code: "IT073",
    item_name: "Salade d’agrumes & menthe",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/salade_agrumes.jpg",
  },
  {
    item_code: "IT074",
    item_name: "Cake citron pavot",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/cake_citron_pavot.jpg",
  },
  {
    item_code: "IT075",
    item_name: "Crème café végétale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/creme_cafe.jpg",
  },
  {
    item_code: "IT076",
    item_name: "Figues rôties au sirop d’érable",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/figues_roties.jpg",
  },
  {
    item_code: "IT077",
    item_name: "Poire rôtie, caramel végétal",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/poire_rotie_caramel.jpg",
  },
  {
    item_code: "IT078",
    item_name: "Tartelette fruits de saison",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tartelette_saison.jpg",
  },
  {
    item_code: "IT079",
    item_name: "Ganache chocolat & fleur de sel",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/ganache_chocolat.jpg",
  },
  {
    item_code: "IT080",
    item_name: "Mousse coco & mangue",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/mousse_coco_mangue.jpg",
  },
  {
    item_code: "IT081",
    item_name: "Clafoutis végétal aux fruits",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/clafoutis_vegan.jpg",
  },
  {
    item_code: "IT082",
    item_name: "Tarte chocolat noisette",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tarte_chocolat_noisette.jpg",
  },
  {
    item_code: "IT083",
    item_name: "Fruits rouges, coulis léger",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/fruits_rouges_coulis.jpg",
  },
  {
    item_code: "IT084",
    item_name: "Moelleux chocolat-amande",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/moelleux_chocolat_amande.jpg",
  },
  {
    item_code: "IT085",
    item_name: "Crème vanille végétale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/creme_vanille.jpg",
  },
  {
    item_code: "IT086",
    item_name: "Pêche rôtie, verveine",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/peche_rotie_verveine.jpg",
  },
  {
    item_code: "IT087",
    item_name: "Glace chocolat vegan",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/glace_chocolat.jpg",
  },

  {
    item_code: "IT059",
    item_name: "Crème brûlée végétale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/creme_brulee.jpg",
  },
  {
    item_code: "IT060",
    item_name: "Tarte aux fruits de saison",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tarte_fruits.jpg",
  },
  {
    item_code: "IT061",
    item_name: "Fondant chocolat noir intense",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/fondant_chocolat.jpg",
  },
  {
    item_code: "IT062",
    item_name: "Mousse chocolat aquafaba",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/mousse_chocolat.jpg",
  },
  {
    item_code: "IT063",
    item_name: "Panna cotta végétale vanille",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/panna_cotta.jpg",
  },
  {
    item_code: "IT064",
    item_name: "Poire pochée épices",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/poire_pochee.jpg",
  },
  {
    item_code: "IT065",
    item_name: "Tiramisu végétal",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tiramisu.jpg",
  },
  {
    item_code: "IT066",
    item_name: "Clafoutis fruits rouges",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/clafoutis.jpg",
  },
  {
    item_code: "IT067",
    item_name: "Cheesecake végétal citron",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/cheesecake.jpg",
  },
  {
    item_code: "IT068",
    item_name: "Île flottante végétale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/ile_flottante.jpg",
  },
  {
    item_code: "IT069",
    item_name: "Tarte tatin végétale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tarte_tatin.jpg",
  },
  {
    item_code: "IT070",
    item_name: "Brownie chocolat noix",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/brownie.jpg",
  },
  {
    item_code: "IT071",
    item_name: "Macaron géant vegan",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/macaron.jpg",
  },
  {
    item_code: "IT072",
    item_name: "Crêpe sucrée chocolat",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/crepe.jpg",
  },
  {
    item_code: "IT073",
    item_name: "Sorbet framboise artisanale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/sorbet.jpg",
  },
  {
    item_code: "IT074",
    item_name: "Pavlova végétale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/pavlova.jpg",
  },
  {
    item_code: "IT075",
    item_name: "Moelleux amande citron",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/moelleux_amande.jpg",
  },
  {
    item_code: "IT076",
    item_name: "Millefeuille végétal",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/millefeuille.jpg",
  },
  {
    item_code: "IT077",
    item_name: "Gâteau chocolat ganache",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/gateau_chocolat.jpg",
  },
  {
    item_code: "IT078",
    item_name: "Compotée pomme cannelle",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/compote_pomme.jpg",
  },
  {
    item_code: "IT079",
    item_name: "Tarte citron meringuée végétale",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tarte_citron.jpg",
  },
  {
    item_code: "IT080",
    item_name: "Cake pistache framboise",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/cake_pistache.jpg",
  },
  {
    item_code: "IT081",
    item_name: "Glace artisanale vanille",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/glace_vanille.jpg",
  },
  {
    item_code: "IT082",
    item_name: "Financier amande",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/financier.jpg",
  },
  {
    item_code: "IT083",
    item_name: "Tarte chocolat praliné",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/tarte_praline.jpg",
  },
  {
    item_code: "IT084",
    item_name: "Crème dessert café",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/creme_cafe.jpg",
  },
  {
    item_code: "IT085",
    item_name: "Gâteau carotte vegan",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/gateau_carotte.jpg",
  },
  {
    item_code: "IT086",
    item_name: "Crumble fruits rouges",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/crumble.jpg",
  },
  {
    item_code: "IT087",
    item_name: "Profiteroles végétales",
    item_type: "dessert",
    diet_type: "Vegan",
    image: "/images/items/profiteroles.jpg",
  },

  {
    item_code: "IT088",
    item_name: "Vin rouge bio Bordeaux",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/vin_rouge.jpg",
  },
  {
    item_code: "IT089",
    item_name: "Vin blanc sec Loire",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/vin_blanc.jpg",
  },
  {
    item_code: "IT090",
    item_name: "Vin rosé Provence",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/vin_rose.jpg",
  },
  {
    item_code: "IT091",
    item_name: "Champagne vegan brut",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/champagne.jpg",
  },
  {
    item_code: "IT092",
    item_name: "Mocktail framboise basilic",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/mocktail.jpg",
  },
  {
    item_code: "IT093",
    item_name: "Eau pétillante premium",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/eau_petillante.jpg",
  },
  {
    item_code: "IT094",
    item_name: "Eau plate minérale",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/eau_plate.jpg",
  },
  {
    item_code: "IT095",
    item_name: "Jus pomme artisanal",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/jus_pomme.jpg",
  },
  {
    item_code: "IT096",
    item_name: "Thé glacé maison",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/the_glace.jpg",
  },
  {
    item_code: "IT097",
    item_name: "Infusion verveine fraîche",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/verveine.jpg",
  },
  {
    item_code: "IT098",
    item_name: "Cidre brut vegan",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/cidre.jpg",
  },
  {
    item_code: "IT099",
    item_name: "Spritz sans alcool",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/spritz.jpg",
  },
  {
    item_code: "IT100",
    item_name: "Kombucha artisanal",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/kombucha.jpg",
  },
  {
    item_code: "IT101",
    item_name: "Vin nature rouge",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/vin_nature.jpg",
  },
  {
    item_code: "IT102",
    item_name: "Vin blanc bio premium",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/vin_blanc_premium.jpg",
  },
  {
    item_code: "IT103",
    item_name: "Rosé gastronomique",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/rose_gastro.jpg",
  },
  {
    item_code: "IT104",
    item_name: "Cocktail agrumes maison",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/cocktail_agrumes.jpg",
  },
  {
    item_code: "IT105",
    item_name: "Jus raisin bio",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/jus_raisin.jpg",
  },
  {
    item_code: "IT106",
    item_name: "Bière artisanale vegan",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/biere.jpg",
  },
  {
    item_code: "IT107",
    item_name: "Vin rouge prestige",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/vin_prestige.jpg",
  },
  {
    item_code: "IT108",
    item_name: "Thé matcha glacé",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/matcha.jpg",
  },
  {
    item_code: "IT109",
    item_name: "Cocktail concombre citron",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/cocktail_concombre.jpg",
  },
  {
    item_code: "IT110",
    item_name: "Vin blanc grand cru vegan",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/grand_cru.jpg",
  },
  {
    item_code: "IT111",
    item_name: "Rosé pétillant",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/rose_petillant.jpg",
  },
  {
    item_code: "IT112",
    item_name: "Café arabica premium",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/cafe.jpg",
  },
  {
    item_code: "IT113",
    item_name: "Chocolat chaud maison",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/chocolat_chaud.jpg",
  },
  {
    item_code: "IT114",
    item_name: "Vin rouge sélection chef",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/vin_chef.jpg",
  },
  {
    item_code: "IT115",
    item_name: "Infusion fruits rouges",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/infusion_fruits.jpg",
  },
  {
    item_code: "IT116",
    item_name: "Mocktail mangue passion",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/mocktail_mangue.jpg",
  },

  {
    item_code: "IT088",
    item_name: "Sélection vin rouge bio",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/vin_rouge_bio.jpg",
  },
  {
    item_code: "IT089",
    item_name: "Sélection vin blanc sec",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/vin_blanc_sec.jpg",
  },
  {
    item_code: "IT090",
    item_name: "Rosé de Provence",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/rose_provence.jpg",
  },
  {
    item_code: "IT091",
    item_name: "Pinot Noir bio",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/pinot_noir.jpg",
  },
  {
    item_code: "IT092",
    item_name: "Chardonnay sec",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/chardonnay.jpg",
  },
  {
    item_code: "IT093",
    item_name: "Chablis bio",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/chablis.jpg",
  },
  {
    item_code: "IT094",
    item_name: "Sancerre blanc",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/sancerre.jpg",
  },
  {
    item_code: "IT095",
    item_name: "Côtes-du-Rhône rouge",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/cotes_rhone.jpg",
  },
  {
    item_code: "IT096",
    item_name: "Pinot Gris sec",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/pinot_gris.jpg",
  },
  {
    item_code: "IT097",
    item_name: "Crémant brut",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/cremant.jpg",
  },
  {
    item_code: "IT098",
    item_name: "Champagne vegan",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/champagne_vegan.jpg",
  },
  {
    item_code: "IT099",
    item_name: "Vin pétillant sans alcool",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/petillant_sans_alcool.jpg",
  },
  {
    item_code: "IT100",
    item_name: "Mocktail agrumes & basilic",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/mocktail_agrumes_basilic.jpg",
  },
  {
    item_code: "IT101",
    item_name: "Eau infusée citron-menthe",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/eau_infusee.jpg",
  },
  {
    item_code: "IT102",
    item_name: "Thé glacé maison",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/the_glace.jpg",
  },
  {
    item_code: "IT103",
    item_name: "Limonade artisanale",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/limonade.jpg",
  },
  {
    item_code: "IT104",
    item_name: "Kombucha artisanal",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/kombucha.jpg",
  },
  {
    item_code: "IT105",
    item_name: "Jus pomme-poire artisanal",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/jus_pomme_poire.jpg",
  },
  {
    item_code: "IT106",
    item_name: "Jus grenade artisanal",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/jus_grenade.jpg",
  },
  {
    item_code: "IT107",
    item_name: "Infusion verveine",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/infusion_verveine.jpg",
  },
  {
    item_code: "IT108",
    item_name: "Café bio sélection",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/cafe_bio.jpg",
  },
  {
    item_code: "IT109",
    item_name: "Eau plate premium",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/eau_plate.jpg",
  },
  {
    item_code: "IT110",
    item_name: "Eau pétillante premium",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/eau_petillante.jpg",
  },
  {
    item_code: "IT111",
    item_name: "Bordeaux rouge vegan",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/bordeaux_rouge.jpg",
  },
  {
    item_code: "IT112",
    item_name: "Bourgogne blanc bio",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/bourgogne_blanc.jpg",
  },
  {
    item_code: "IT113",
    item_name: "Syrah biologique",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/syrah.jpg",
  },
  {
    item_code: "IT114",
    item_name: "Saint-Émilion Grand Cru (vegan)",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/saint_emilion.jpg",
  },
  {
    item_code: "IT115",
    item_name: "Rosé sec vegan",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/rose_sec.jpg",
  },
  {
    item_code: "IT116",
    item_name: "Côtes-de-Provence rosé",
    item_type: "drink",
    diet_type: "Vegan",
    image: "/images/items/cotes_provence.jpg",
  },
];

export interface LameMenus {
  item_code: string;
  item_name: string;
  item_type: string;
  diet_type: string;
  image: string;
}

const seedItMenu = async (data: LameMenus[]) => {
  let shitCount = 0;
  for (let x of data) {
    shitCount += 1;
    await pgPool.query(
      `Insert into menu_items(
        item_name,
        item_type,
        min_no_persons,
        is_active,
        diet_type,
        min_preparation_time,
        in_stock,
        image_url
        ) VALUES(
         $1,$2,$3,$4,$5,$6,$7,$8)`,
      [x.item_name, x.item_type, 2, true, x.diet_type, 15, +1, x.image],
    );
  }
  return console.log(`${shitCount} items successfuly loaded`);
};
seedItMenu(vaganData);
